[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
remappings = ["forge-std/=lib/forge-std/src/", "curta/=lib/curta/src/"]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
func_attrs_with_params_multiline = false
quote_style = "double"
number_underscore = "thousands"

[etherscan]
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
eth = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api" }

[rpc_endpoints]
base = "${RPC_URL_BASE}"
eth = "${RPC_URL_ETH}"
